name: Build Web Docker Image

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hz/dify-web:1.3.10 ./web
          docker save hz/dify-web:1.3.10 | gzip > hz_dify-web_1.3.10.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: hz_dify-web_1.3.10.tar.gz
          retention-days: 5  # 设置文件保留天数